// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/delivery_request.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequestInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weight        float32                `protobuf:"fixed32,1,opt,name=weight,proto3" json:"weight,omitempty"`
	FromLocation  string                 `protobuf:"bytes,2,opt,name=from_location,json=fromLocation,proto3" json:"from_location,omitempty"`
	ToLocation    string                 `protobuf:"bytes,3,opt,name=to_location,json=toLocation,proto3" json:"to_location,omitempty"`
	PreferredDate string                 `protobuf:"bytes,4,opt,name=preferred_date,json=preferredDate,proto3" json:"preferred_date,omitempty"`
	CreatedBy     int32                  `protobuf:"varint,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	ResponsibleId int32                  `protobuf:"varint,6,opt,name=responsible_id,json=responsibleId,proto3" json:"responsible_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequestInput) Reset() {
	*x = CreateRequestInput{}
	mi := &file_proto_delivery_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestInput) ProtoMessage() {}

func (x *CreateRequestInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestInput.ProtoReflect.Descriptor instead.
func (*CreateRequestInput) Descriptor() ([]byte, []int) {
	return file_proto_delivery_request_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequestInput) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateRequestInput) GetFromLocation() string {
	if x != nil {
		return x.FromLocation
	}
	return ""
}

func (x *CreateRequestInput) GetToLocation() string {
	if x != nil {
		return x.ToLocation
	}
	return ""
}

func (x *CreateRequestInput) GetPreferredDate() string {
	if x != nil {
		return x.PreferredDate
	}
	return ""
}

func (x *CreateRequestInput) GetCreatedBy() int32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *CreateRequestInput) GetResponsibleId() int32 {
	if x != nil {
		return x.ResponsibleId
	}
	return 0
}

func (x *CreateRequestInput) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequestResponse) Reset() {
	*x = CreateRequestResponse{}
	mi := &file_proto_delivery_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequestResponse) ProtoMessage() {}

func (x *CreateRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequestResponse.ProtoReflect.Descriptor instead.
func (*CreateRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_delivery_request_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequestResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetRequestInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StatusId      *wrapperspb.Int32Value `protobuf:"bytes,2,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequestInput) Reset() {
	*x = GetRequestInput{}
	mi := &file_proto_delivery_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestInput) ProtoMessage() {}

func (x *GetRequestInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestInput.ProtoReflect.Descriptor instead.
func (*GetRequestInput) Descriptor() ([]byte, []int) {
	return file_proto_delivery_request_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequestInput) GetUserId() *wrapperspb.Int32Value {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *GetRequestInput) GetStatusId() *wrapperspb.Int32Value {
	if x != nil {
		return x.StatusId
	}
	return nil
}

type GetRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*DeliveryRequest     `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequestResponse) Reset() {
	*x = GetRequestResponse{}
	mi := &file_proto_delivery_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestResponse) ProtoMessage() {}

func (x *GetRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestResponse.ProtoReflect.Descriptor instead.
func (*GetRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_delivery_request_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequestResponse) GetRequests() []*DeliveryRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type DeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Weight        float32                `protobuf:"fixed32,2,opt,name=weight,proto3" json:"weight,omitempty"`
	FromLocation  string                 `protobuf:"bytes,3,opt,name=from_location,json=fromLocation,proto3" json:"from_location,omitempty"`
	ToLocation    string                 `protobuf:"bytes,4,opt,name=to_location,json=toLocation,proto3" json:"to_location,omitempty"`
	PreferredDate string                 `protobuf:"bytes,5,opt,name=preferred_date,json=preferredDate,proto3" json:"preferred_date,omitempty"`
	CreatedBy     int32                  `protobuf:"varint,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	ResponsibleId int32                  `protobuf:"varint,7,opt,name=responsible_id,json=responsibleId,proto3" json:"responsible_id,omitempty"`
	StatusId      int32                  `protobuf:"varint,8,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryRequest) Reset() {
	*x = DeliveryRequest{}
	mi := &file_proto_delivery_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryRequest) ProtoMessage() {}

func (x *DeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryRequest.ProtoReflect.Descriptor instead.
func (*DeliveryRequest) Descriptor() ([]byte, []int) {
	return file_proto_delivery_request_proto_rawDescGZIP(), []int{4}
}

func (x *DeliveryRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeliveryRequest) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *DeliveryRequest) GetFromLocation() string {
	if x != nil {
		return x.FromLocation
	}
	return ""
}

func (x *DeliveryRequest) GetToLocation() string {
	if x != nil {
		return x.ToLocation
	}
	return ""
}

func (x *DeliveryRequest) GetPreferredDate() string {
	if x != nil {
		return x.PreferredDate
	}
	return ""
}

func (x *DeliveryRequest) GetCreatedBy() int32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *DeliveryRequest) GetResponsibleId() int32 {
	if x != nil {
		return x.ResponsibleId
	}
	return 0
}

func (x *DeliveryRequest) GetStatusId() int32 {
	if x != nil {
		return x.StatusId
	}
	return 0
}

func (x *DeliveryRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UpdateRequestInput struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Weight        *wrapperspb.FloatValue  `protobuf:"bytes,1,opt,name=weight,proto3" json:"weight,omitempty"`
	FromLocation  *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=from_location,json=fromLocation,proto3" json:"from_location,omitempty"`
	ToLocation    *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=to_location,json=toLocation,proto3" json:"to_location,omitempty"`
	PreferredDate *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=preferred_date,json=preferredDate,proto3" json:"preferred_date,omitempty"`
	ResponsibleId *wrapperspb.Int32Value  `protobuf:"bytes,5,opt,name=responsible_id,json=responsibleId,proto3" json:"responsible_id,omitempty"`
	StatusId      *wrapperspb.Int32Value  `protobuf:"bytes,6,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	RequestId     *wrapperspb.Int32Value  `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequestInput) Reset() {
	*x = UpdateRequestInput{}
	mi := &file_proto_delivery_request_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequestInput) ProtoMessage() {}

func (x *UpdateRequestInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_request_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequestInput.ProtoReflect.Descriptor instead.
func (*UpdateRequestInput) Descriptor() ([]byte, []int) {
	return file_proto_delivery_request_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequestInput) GetWeight() *wrapperspb.FloatValue {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *UpdateRequestInput) GetFromLocation() *wrapperspb.StringValue {
	if x != nil {
		return x.FromLocation
	}
	return nil
}

func (x *UpdateRequestInput) GetToLocation() *wrapperspb.StringValue {
	if x != nil {
		return x.ToLocation
	}
	return nil
}

func (x *UpdateRequestInput) GetPreferredDate() *wrapperspb.StringValue {
	if x != nil {
		return x.PreferredDate
	}
	return nil
}

func (x *UpdateRequestInput) GetResponsibleId() *wrapperspb.Int32Value {
	if x != nil {
		return x.ResponsibleId
	}
	return nil
}

func (x *UpdateRequestInput) GetStatusId() *wrapperspb.Int32Value {
	if x != nil {
		return x.StatusId
	}
	return nil
}

func (x *UpdateRequestInput) GetRequestId() *wrapperspb.Int32Value {
	if x != nil {
		return x.RequestId
	}
	return nil
}

type UpdateRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequestResponse) Reset() {
	*x = UpdateRequestResponse{}
	mi := &file_proto_delivery_request_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequestResponse) ProtoMessage() {}

func (x *UpdateRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_request_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequestResponse.ProtoReflect.Descriptor instead.
func (*UpdateRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_delivery_request_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteRequestInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequestInput) Reset() {
	*x = DeleteRequestInput{}
	mi := &file_proto_delivery_request_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequestInput) ProtoMessage() {}

func (x *DeleteRequestInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_request_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequestInput.ProtoReflect.Descriptor instead.
func (*DeleteRequestInput) Descriptor() ([]byte, []int) {
	return file_proto_delivery_request_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequestInput) GetRequestId() *wrapperspb.Int32Value {
	if x != nil {
		return x.RequestId
	}
	return nil
}

type DeleteRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequestResponse) Reset() {
	*x = DeleteRequestResponse{}
	mi := &file_proto_delivery_request_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequestResponse) ProtoMessage() {}

func (x *DeleteRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_delivery_request_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequestResponse.ProtoReflect.Descriptor instead.
func (*DeleteRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_delivery_request_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_delivery_request_proto protoreflect.FileDescriptor

const file_proto_delivery_request_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/delivery_request.proto\x12\x03drs\x1a\x17validate/validate.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xc0\x02\n" +
	"\x12CreateRequestInput\x12\"\n" +
	"\x06weight\x18\x01 \x01(\x02B\n" +
	"\xfaB\a\n" +
	"\x05%\x00\x00\x00\x00R\x06weight\x12,\n" +
	"\rfrom_location\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\ffromLocation\x12(\n" +
	"\vto_location\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"toLocation\x12.\n" +
	"\x0epreferred_date\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\rpreferredDate\x12&\n" +
	"\n" +
	"created_by\x18\x05 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\tcreatedBy\x12.\n" +
	"\x0eresponsible_id\x18\x06 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\rresponsibleId\x12&\n" +
	"\n" +
	"created_at\x18\a \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tcreatedAt\"6\n" +
	"\x15CreateRequestResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\x81\x01\n" +
	"\x0fGetRequestInput\x124\n" +
	"\auser_id\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x06userId\x128\n" +
	"\tstatus_id\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\bstatusId\"F\n" +
	"\x12GetRequestResponse\x120\n" +
	"\brequests\x18\x01 \x03(\v2\x14.drs.DeliveryRequestR\brequests\"\xa8\x02\n" +
	"\x0fDeliveryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x02R\x06weight\x12#\n" +
	"\rfrom_location\x18\x03 \x01(\tR\ffromLocation\x12\x1f\n" +
	"\vto_location\x18\x04 \x01(\tR\n" +
	"toLocation\x12%\n" +
	"\x0epreferred_date\x18\x05 \x01(\tR\rpreferredDate\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\x05R\tcreatedBy\x12%\n" +
	"\x0eresponsible_id\x18\a \x01(\x05R\rresponsibleId\x12\x1b\n" +
	"\tstatus_id\x18\b \x01(\x05R\bstatusId\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"\x9d\x04\n" +
	"\x12UpdateRequestInput\x12A\n" +
	"\x06weight\x18\x01 \x01(\v2\x1b.google.protobuf.FloatValueB\f\xfaB\t\n" +
	"\a%\x00\x00\x00\x00@\x01R\x06weight\x12M\n" +
	"\rfrom_location\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueB\n" +
	"\xfaB\ar\x05\x10\x01\xd0\x01\x01R\ffromLocation\x12I\n" +
	"\vto_location\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueB\n" +
	"\xfaB\ar\x05\x10\x01\xd0\x01\x01R\n" +
	"toLocation\x12O\n" +
	"\x0epreferred_date\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueB\n" +
	"\xfaB\ar\x05\x10\x01\xd0\x01\x01R\rpreferredDate\x12M\n" +
	"\x0eresponsible_id\x18\x05 \x01(\v2\x1b.google.protobuf.Int32ValueB\t\xfaB\x06\x1a\x04 \x00@\x01R\rresponsibleId\x12C\n" +
	"\tstatus_id\x18\x06 \x01(\v2\x1b.google.protobuf.Int32ValueB\t\xfaB\x06\x1a\x04 \x00@\x01R\bstatusId\x12E\n" +
	"\n" +
	"request_id\x18\a \x01(\v2\x1b.google.protobuf.Int32ValueB\t\xfaB\x06\x1a\x04 \x00@\x00R\trequestId\"1\n" +
	"\x15UpdateRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"P\n" +
	"\x12DeleteRequestInput\x12:\n" +
	"\n" +
	"request_id\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\trequestId\"1\n" +
	"\x15DeleteRequestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa7\x02\n" +
	"\x16DeliveryRequestService\x12D\n" +
	"\rCreateRequest\x12\x17.drs.CreateRequestInput\x1a\x1a.drs.CreateRequestResponse\x12;\n" +
	"\n" +
	"GetRequest\x12\x14.drs.GetRequestInput\x1a\x17.drs.GetRequestResponse\x12D\n" +
	"\rUpdateRequest\x12\x17.drs.UpdateRequestInput\x1a\x1a.drs.UpdateRequestResponse\x12D\n" +
	"\rDeleteRequest\x12\x17.drs.DeleteRequestInput\x1a\x1a.drs.DeleteRequestResponseB\x11Z\x0fdrs/proto;protob\x06proto3"

var (
	file_proto_delivery_request_proto_rawDescOnce sync.Once
	file_proto_delivery_request_proto_rawDescData []byte
)

func file_proto_delivery_request_proto_rawDescGZIP() []byte {
	file_proto_delivery_request_proto_rawDescOnce.Do(func() {
		file_proto_delivery_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_delivery_request_proto_rawDesc), len(file_proto_delivery_request_proto_rawDesc)))
	})
	return file_proto_delivery_request_proto_rawDescData
}

var file_proto_delivery_request_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_delivery_request_proto_goTypes = []any{
	(*CreateRequestInput)(nil),     // 0: drs.CreateRequestInput
	(*CreateRequestResponse)(nil),  // 1: drs.CreateRequestResponse
	(*GetRequestInput)(nil),        // 2: drs.GetRequestInput
	(*GetRequestResponse)(nil),     // 3: drs.GetRequestResponse
	(*DeliveryRequest)(nil),        // 4: drs.DeliveryRequest
	(*UpdateRequestInput)(nil),     // 5: drs.UpdateRequestInput
	(*UpdateRequestResponse)(nil),  // 6: drs.UpdateRequestResponse
	(*DeleteRequestInput)(nil),     // 7: drs.DeleteRequestInput
	(*DeleteRequestResponse)(nil),  // 8: drs.DeleteRequestResponse
	(*wrapperspb.Int32Value)(nil),  // 9: google.protobuf.Int32Value
	(*wrapperspb.FloatValue)(nil),  // 10: google.protobuf.FloatValue
	(*wrapperspb.StringValue)(nil), // 11: google.protobuf.StringValue
}
var file_proto_delivery_request_proto_depIdxs = []int32{
	9,  // 0: drs.GetRequestInput.user_id:type_name -> google.protobuf.Int32Value
	9,  // 1: drs.GetRequestInput.status_id:type_name -> google.protobuf.Int32Value
	4,  // 2: drs.GetRequestResponse.requests:type_name -> drs.DeliveryRequest
	10, // 3: drs.UpdateRequestInput.weight:type_name -> google.protobuf.FloatValue
	11, // 4: drs.UpdateRequestInput.from_location:type_name -> google.protobuf.StringValue
	11, // 5: drs.UpdateRequestInput.to_location:type_name -> google.protobuf.StringValue
	11, // 6: drs.UpdateRequestInput.preferred_date:type_name -> google.protobuf.StringValue
	9,  // 7: drs.UpdateRequestInput.responsible_id:type_name -> google.protobuf.Int32Value
	9,  // 8: drs.UpdateRequestInput.status_id:type_name -> google.protobuf.Int32Value
	9,  // 9: drs.UpdateRequestInput.request_id:type_name -> google.protobuf.Int32Value
	9,  // 10: drs.DeleteRequestInput.request_id:type_name -> google.protobuf.Int32Value
	0,  // 11: drs.DeliveryRequestService.CreateRequest:input_type -> drs.CreateRequestInput
	2,  // 12: drs.DeliveryRequestService.GetRequest:input_type -> drs.GetRequestInput
	5,  // 13: drs.DeliveryRequestService.UpdateRequest:input_type -> drs.UpdateRequestInput
	7,  // 14: drs.DeliveryRequestService.DeleteRequest:input_type -> drs.DeleteRequestInput
	1,  // 15: drs.DeliveryRequestService.CreateRequest:output_type -> drs.CreateRequestResponse
	3,  // 16: drs.DeliveryRequestService.GetRequest:output_type -> drs.GetRequestResponse
	6,  // 17: drs.DeliveryRequestService.UpdateRequest:output_type -> drs.UpdateRequestResponse
	8,  // 18: drs.DeliveryRequestService.DeleteRequest:output_type -> drs.DeleteRequestResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_delivery_request_proto_init() }
func file_proto_delivery_request_proto_init() {
	if File_proto_delivery_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_delivery_request_proto_rawDesc), len(file_proto_delivery_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_delivery_request_proto_goTypes,
		DependencyIndexes: file_proto_delivery_request_proto_depIdxs,
		MessageInfos:      file_proto_delivery_request_proto_msgTypes,
	}.Build()
	File_proto_delivery_request_proto = out.File
	file_proto_delivery_request_proto_goTypes = nil
	file_proto_delivery_request_proto_depIdxs = nil
}
